version: '2'
services:
  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     networks:
       - backend
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
  db:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  lb:
    image: dockercloud/haproxy
    depends_on:
      - wordpress
    ports:
      - 80:80
    networks:
      - backend
      - public
    environment:
      - ADDITIONAL_SERVICES=composewordpress:wordpress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  public:
    driver: bridge
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.223.0/24
          gateway: 192.168.223.1
volumes:
    db_data:
      driver: local


